### ISSUE TITLE
Implement Recipe Ingredient Distance Cost

### ISSUE THREAD

**Issue by joseram97** [recipedia-uofa/recipedia#110]
**REQ 2-2**: Recipe Ingredient Distance Cost. Apply a cost function on recipes that ranks recipes based on how many ingredients are missing from the recipe. A recipe where all ingredients are matched should have a low distance (likely 0). On the other hand, a recipe with few to no matched ingredients should have a high distance.

**Comment by jhryniw** [comment]
closed by #124
